spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/pratice
    username: sa
    passwrod:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #parameter
    #      naming:
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy #underscore
    properties:
      show_sql: true
      format_sql: true
      use_sql_comment: true
      default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
